### ISSUE TITLE
Don't see any prediction with rs serve

### ISSUE THREAD

**Issue by iboates** [mapbox/robosat#218]
I am running the test Flask server on my GPU server, and it launches successfully but when I pan around, I don't get any results. This is supposed to be live prediction right? Or have I misunderstood?

I loaded my model checkpoint onto the server and then ran the server like this:

`./rs serve --model vineyards/config/model-unet.toml --dataset vineyards/config/model-unet.toml --url https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}@2x.png --checkpoint ../checkpoint-00012-of-00100.pth --host=0.0.0.0`

I have exported my mapbox token before this and have double-checked the paths to my model and dataset. But when I go to the page, I just see the satellite tiles and no prediction on top. Any ideas?

 I don't even see any activity in the console output from Flask, nor any GPU activity from `nvidia-smi` when panning around.

I do notice however that the request is made in the browser to 127.0.0.1, but this would be pointing to my own local machine where I have the browser open, is there a way to get it to put to the source server itself?

![image](https://user-images.githubusercontent.com/13814358/114060601-d40b6e00-9895-11eb-8772-85dd87d41377.png)

**Comment by daniel-j-h** [comment]
Here are the two files you need to look at
- https://github.com/mapbox/robosat/blob/cbb1c73328183afd2d6351b7bfa3f430b73103ea/robosat/tools/templates/map.html
- https://github.com/mapbox/robosat/blob/cbb1c73328183afd2d6351b7bfa3f430b73103ea/robosat/tools/serve.py

The browser makes requests to localhost here

https://github.com/mapbox/robosat/blob/cbb1c73328183afd2d6351b7bfa3f430b73103ea/robosat/tools/templates/map.html#L74

If you run the serve tool on your gpu rig and change the line above to the gpu rig's ip it should work. As long as the html and the tiles are served from the same origin (host & port) you will be fine re. CORS, otherwise you probably need to add some CORS headers.

Also check the note in the readme please :bow:

https://github.com/mapbox/robosat/blob/cbb1c73328183afd2d6351b7bfa3f430b73103ea/README.md

**Comment by iboates** [comment]
@daniel-j-h Thanks for the tip, I didn't realize it was baked into the index.html. I was able to get it running.

RE: the note - just wondering what you meant by that, do you mean to say to not expect consistent support with issues on this github anymore?

**Comment by daniel-j-h** [comment]
Glad you got it running! :tada: 

Exactly, this project is outdated by now for years and the Mapbox folks don't maintain it :crying_cat_face: Just want to be clear about this before folks put their time and effort into an abandoned project.

**Comment by iboates** [comment]
Ok, understood. I have my own hacked fork specifically for my purposes anyway. Is there a new project for the same purpose? Mapbox-affiliated or not. I saw that there was Robosat.pink but it seems that the creator actually passed away and nobody has maintained it since then.

**Comment by daniel-j-h** [comment]
Yes, sadly https://github.com/mapbox/robosat/issues/184

I'm not keeping track of the current state wrt. open source solutions in the robosat domain, sorry.

I do work on my own machine learning projects and can say with confidence that robosat by now could be orders of magnitude faster, cheaper to train/predict, and more accurate, with all the recent advances, tho.

Best,
Daniel
