### ISSUE TITLE
Fetch neighbouring images when downloading

### ISSUE THREAD

**Issue by tomass** [mapbox/robosat#49]
Buffer from neighbouring images is added to the image being used for training (_robosat/tiles.py#buffer_tile_image_). Maybe `rs download` should try fetching images neighbouring the ones in csv file?
For example: if training set is made of three images (marked as _T_), maybe neighbouring images (marked as _N_) should also be downloaded:
```
.NNN
NNTN
NTTN
NNNN
```
This would decrease (or in most cases totally eradicate) the need to add "no data" or "mirroring" buffers?

**Comment by daniel-j-h** [comment]
We only buffer images for prediction currently. For training we need fixed-size images and buffering would only give us images which are a bit larger. In contrast for prediction we buffer, predict, then unbuffer the prediction. The main use-case is to have smooth tile borders from prediction.

https://github.com/mapbox/robosat/blob/8d9bd9cbf1edde83f531d267072b6dcb3ba93860/robosat/datasets.py#L81-L134

For prediction your dataset should already come with neighboring tiles, e.g. because you tiled a GeoTIFF or you downloaded a full set of tiles for a bounding box.

What's your take on this? Do you have a use-case where the downloader should fetch neighboring tiles?

**Comment by tomass** [comment]
Well I'm not an expert in ML, but I've heard that if you want to have a good training for points, you need their neighbours (moving window). Therefore if you want good training for points close to the edge of an image, you would need a part of the neighbouring image. But this could be something which depends on the model used.
I'm fine with closing this issue if buffering is not used during training.

**Comment by daniel-j-h** [comment]
The problem for training is you need a fixed-size image. We can change the tile size from our default 256x256 or 512x512 but then you still will have a fixed size image tile. You will always have borders with fixed size images.

The only reason why we need buffering is to handle predictions near / across tile boundaries during. That's independent to raw model training or prediction on its own and is really just to allow for smooth transitions between tiles.

**Comment by daniel-j-h** [comment]
Adding here: one use-case I can think of is if you have a dataset with a strong bias, for example a single x or y slippy map strip with no data in half of your tiles. Then you probably need a sliding window approach.

I'm closing this as not actionable; we use slippy map tiles as abstraction to work with fixed-size image tiles.
